# Generated by Django 3.1.5 on 2021-04-05 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Utils', '0002_auto_20210405_2038'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
