# Generated by Django 3.2 on 2021-04-23 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utils', '0005_contact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 23, 16, 17, 48, 530310)),
        ),
    ]
