# Generated by Django 3.2 on 2021-04-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utils', '0006_alter_contact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
