# Generated by Django 3.2 on 2021-04-23 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Utils', '0007_alter_contact_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contacts',
        ),
    ]
